import { mkdir, writeFile } from 'fs/promises';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { slugify } from './storage.js';
import { STEMS_DIR } from './stems.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

export const REAPER_SCRIPT_DIR = join(__dirname, '../../stems/reaper');

export function defaultReaperStemScriptPath(name) {
  return join(STEMS_DIR, 'reaper', `${slugify(name) || 'stems'}-import.lua`);
}

export function buildReaperStemImportScript(manifest, options = {}) {
  const bpm = normalizeBpm(options.bpm);
  const timeSignature = parseTimeSignature(options.timeSignature || '4/4');
  const groupFolders = options.groupFolders !== false;
  const projectName = String(options.projectName || manifest.name || 'Stem Import').trim() || 'Stem Import';

  const trackEntries = buildTrackEntries(manifest.stems || []);
  const groupedEntries = groupFolders ? groupTrackEntries(trackEntries) : [];

  const lines = [
    '-- Generated by ableton-composer',
    `-- Source manifest: ${manifest.name || 'stems'}`,
    '',
    `local project_name = ${luaString(projectName)}`,
    `local bpm = ${formatNumber(bpm)}`,
    `local time_sig_num = ${timeSignature[0]}`,
    `local time_sig_denom = ${timeSignature[1]}`,
    `local use_group_folders = ${groupFolders ? 'true' : 'false'}`,
    '',
    'local stems = {',
    ...trackEntries.map(entry => `  ${serializeLuaTable(entry)},`),
    '}',
    '',
    groupFolders ? 'local grouped = {' : 'local grouped = nil',
    ...(groupFolders
      ? groupedEntries.map(group => `  ${serializeLuaTable(group)},`)
      : []),
    ...(groupFolders ? ['}'] : []),
    '',
    'local color_map = {',
    ...Object.entries(REAPER_COLOR_MAP).map(([name, rgb]) => `  [${luaString(name)}] = { ${rgb.join(', ')} },`),
    '}',
    '',
    'local function set_track_name(track, name)',
    '  reaper.GetSetMediaTrackInfo_String(track, "P_NAME", name, true)',
    'end',
    '',
    'local function set_track_color(track, color_name)',
    '  local rgb = color_map[color_name or ""]',
    '  if not rgb then return end',
    '  local native = reaper.ColorToNative(rgb[1], rgb[2], rgb[3]) | 0x1000000',
    '  reaper.SetTrackColor(track, native)',
    'end',
    '',
    'local function clear_track_selection()',
    '  for i = 0, reaper.CountTracks(0) - 1 do',
    '    reaper.SetTrackSelected(reaper.GetTrack(0, i), false)',
    '  end',
    'end',
    '',
    'local function insert_track(track_index)',
    '  reaper.InsertTrackAtIndex(track_index, false)',
    '  return reaper.GetTrack(0, track_index)',
    'end',
    '',
    'local function insert_stem(track, stem)',
    '  if not reaper.file_exists(stem.file) then',
    '    return false, "missing file: " .. stem.file',
    '  end',
    '  clear_track_selection()',
    '  reaper.SetTrackSelected(track, true)',
    '  reaper.InsertMedia(stem.file, 0)',
    '  return true, nil',
    'end',
    '',
    'local function apply_project_tempo()',
    '  reaper.SetTempoTimeSigMarker(0, -1, 0, -1, -1, bpm, time_sig_num, time_sig_denom, false)',
    'end',
    '',
    'local function build_flat()',
    '  local insert_at = reaper.CountTracks(0)',
    '  local imported = 0',
    '  local missing = {}',
    '  for _, stem in ipairs(stems) do',
    '    local track = insert_track(insert_at)',
    '    set_track_name(track, stem.track_name)',
    '    set_track_color(track, stem.color)',
    '    local ok, err = insert_stem(track, stem)',
    '    if ok then imported = imported + 1 else missing[#missing + 1] = err end',
    '    insert_at = insert_at + 1',
    '  end',
    '  return imported, missing',
    'end',
    '',
    'local function build_grouped()',
    '  local insert_at = reaper.CountTracks(0)',
    '  local imported = 0',
    '  local missing = {}',
    '  for _, group in ipairs(grouped) do',
    '    local folder = insert_track(insert_at)',
    '    set_track_name(folder, group.name)',
    '    set_track_color(folder, group.color)',
    '    reaper.SetMediaTrackInfo_Value(folder, "I_FOLDERDEPTH", 1)',
    '    insert_at = insert_at + 1',
    '',
    '    for stem_index, stem in ipairs(group.stems) do',
    '      local track = insert_track(insert_at)',
    '      set_track_name(track, stem.track_name)',
    '      set_track_color(track, stem.color)',
    '      if stem_index == #group.stems then',
    '        reaper.SetMediaTrackInfo_Value(track, "I_FOLDERDEPTH", -1)',
    '      end',
    '      local ok, err = insert_stem(track, stem)',
    '      if ok then imported = imported + 1 else missing[#missing + 1] = err end',
    '      insert_at = insert_at + 1',
    '    end',
    '  end',
    '  return imported, missing',
    'end',
    '',
    'reaper.Undo_BeginBlock()',
    'reaper.PreventUIRefresh(1)',
    '',
    'apply_project_tempo()',
    'local imported, missing',
    'if use_group_folders and grouped and #grouped > 0 then',
    '  imported, missing = build_grouped()',
    'else',
    '  imported, missing = build_flat()',
    'end',
    '',
    'clear_track_selection()',
    'reaper.TrackList_AdjustWindows(false)',
    'reaper.UpdateArrange()',
    'reaper.PreventUIRefresh(-1)',
    'reaper.Undo_EndBlock("Import stem manifest into REAPER: " .. project_name, -1)',
    '',
    'if #missing > 0 then',
    '  reaper.ShowConsoleMsg("Imported " .. imported .. " stem(s) into " .. project_name .. "\\n")',
    '  reaper.ShowConsoleMsg("Missing files:\\n" .. table.concat(missing, "\\n") .. "\\n")',
    '  reaper.ShowMessageBox("Imported " .. imported .. " stem(s). Some files were missing; open the ReaScript console for details.", "ableton-composer", 0)',
    'else',
    '  reaper.ShowMessageBox("Imported " .. imported .. " stem(s) into " .. project_name .. ".", "ableton-composer", 0)',
    'end',
    '',
  ];

  return `${lines.join('\n')}\n`;
}

export async function writeReaperStemImportScript(outputPath, script) {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, script, 'utf-8');
  return outputPath;
}

function buildTrackEntries(stems) {
  const occurrences = new Map();

  return stems.map((stem, index) => {
    const baseName = String(stem.track_name || stem.filename || `Stem ${index + 1}`).trim() || `Stem ${index + 1}`;
    const seen = (occurrences.get(baseName) || 0) + 1;
    occurrences.set(baseName, seen);

    return {
      id: stem.id || `stem-${index + 1}`,
      group: stem.group || 'Music',
      role: stem.role || 'other',
      color: stem.color || null,
      file: String(stem.source_path || ''),
      track_name: seen === 1 ? baseName : `${baseName} ${seen}`,
    };
  });
}

function groupTrackEntries(entries) {
  const groups = new Map();

  for (const entry of entries) {
    const name = entry.group || 'Music';
    if (!groups.has(name)) {
      groups.set(name, {
        name,
        color: colorForGroup(name),
        stems: [],
      });
    }
    groups.get(name).stems.push(entry);
  }

  return [...groups.values()].sort((a, b) => a.name.localeCompare(b.name, 'en'));
}

function colorForGroup(group) {
  const canonical = {
    Drums: 'red',
    Bass: 'blue',
    Music: 'purple',
    Vocals: 'green',
    FX: 'yellow',
  }[group];

  return canonical || 'gray';
}

function normalizeBpm(value) {
  const bpm = Number(value || 120);
  if (!Number.isFinite(bpm) || bpm <= 0) {
    throw new Error(`Invalid BPM: ${value}`);
  }
  return bpm;
}

function parseTimeSignature(value) {
  const match = String(value || '4/4').trim().match(/^(\d+)\s*\/\s*(\d+)$/);
  if (!match) {
    throw new Error(`Invalid time signature: ${value}. Use values like "4/4" or "3/4".`);
  }

  const numerator = Number(match[1]);
  const denominator = Number(match[2]);
  if (!Number.isInteger(numerator) || numerator <= 0 || !Number.isInteger(denominator) || denominator <= 0) {
    throw new Error(`Invalid time signature: ${value}. Use positive integers like "4/4".`);
  }

  return [numerator, denominator];
}

function serializeLuaTable(value) {
  if (Array.isArray(value)) {
    return `{ ${value.map(serializeLuaValue).join(', ')} }`;
  }

  const entries = Object.entries(value).map(([key, item]) => `${key} = ${serializeLuaValue(item)}`);
  return `{ ${entries.join(', ')} }`;
}

function serializeLuaValue(value) {
  if (Array.isArray(value)) return serializeLuaTable(value);
  if (value && typeof value === 'object') return serializeLuaTable(value);
  if (typeof value === 'string') return luaString(value);
  if (typeof value === 'number') return formatNumber(value);
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (value == null) return 'nil';
  return luaString(String(value));
}

function luaString(value) {
  return `"${String(value)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n')}"`;
}

function formatNumber(value) {
  return Number.isInteger(value) ? String(value) : String(Number(value.toFixed(6)));
}

const REAPER_COLOR_MAP = {
  red: [224, 76, 76],
  blue: [66, 133, 244],
  purple: [142, 68, 173],
  green: [52, 168, 83],
  yellow: [244, 180, 0],
  gray: [128, 128, 128],
};
